
--즐겨찾기가 가장 많은 식당 정보 출력하기

SELECT FOOD_TYPE, REST_ID, REST_NAME,FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE,FAVORITES) IN 
(
SELECT FOOD_TYPE, MAX(FAVORITES)
FROM REST_INFO
GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC

--없어진 기록 찾기
SELECT *
FROM (
(SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
)
MINUS 
(SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS)
)
ORDER BY ANIMAL_ID